export enum CartActions {
    ADD_PRODUCT = "ADD_PRODUCT",
    SUBSTRACT_PRODUCT = "SUBSTRACT_PRODUCT",
    REMOVE_PRODUCT = "REMOVE_PRODUCT",
    UPDATE_CART = "UPDATE_CART"
}

export enum UserActions {
    REGISTER = "REGISTER",
    LOGIN = "LOGIN",
    WATCH = "WATCH",
    UPDATE_GUEST_TOKEN = "UPDATE_GUEST_TOKEN",
    LOGOUT = "LOGOUT"
}

export enum FetchActions {
    FETCH_BEGIN = "FETCH_BEGIN",
    FETCH_FINISH = "FETCH_FINISH",
}